# Generated by Django 2.2.1 on 2019-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('term', models.IntegerField()),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
