# Generated by Django 2.2.1 on 2019-05-16 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_api', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='loan_api.Client'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('made', 'made'), ('missed', 'missed')], max_length=6, verbose_name='Payment')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_api.Loan')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
