# Generated by Django 2.2.1 on 2019-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_api', '0003_auto_20190516_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
